#!/bin/bash

if [ ! -d ".git" ]; then
    echo "Not a git repository"
    exit 0
fi

BASENAME=$(basename $PWD | cut -d'-' -f1-1)
BRANCH=$(git branch | grep \* | cut -d '_' -f1-1 | cut -c3-)

cat ~/git/dea-commit-template | sed 's/TASK/'"$BRANCH"'/' | sed 's/PROJECT/'"$BASENAME"'/' > ~/git/commit-template
git commit -t ~/git/commit-template
